### PR TITLE
Handle 3rd party packages in src

### PR DESCRIPTION
**Pull request by pcraciunoiu**
Including editable packages. Any package installed in src instead of site-packages would have this issue.

The tricky thing is, with virtualenvs, the path could be anywhere, so can't rely on `.venv` detection either.

Example:

```sh
pip install -e git+https://github.com/etianen/django-reversion.git#egg=reversion
# add reversion to INSTALLED_APPS
./manage.py runserver
```

Expected: works fine.

Actual:

```
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (dlm.E001) reversion's max_migration.txt does not exist.
	HINT: If you just installed django-linear-migrations, run 'python manage.py create-max-migration-files'. Otherwise, check how it has gone missing.
```

This fixes the issue. Not 100% sure it's the best solution, but it seems like a reliable way to detect pip-installed packages.

### CODE REVIEW

**Review by adamchainz — COMMENTED** [review]
Hi

I appreciate this doesn't work but I don't think using a pip internal is appropriate. Maybe importlib-metadata can work?

As for solving your immediate problem, you can probably switch from an editable install to a tarball install, which is also faster, as I outline in this article: https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/

**Comment by pcraciunoiu** [comment]
I can look at importlib-metadata and see about updating this.

My immediate problem is that a package from GitHub (which is private), installs into `src` even without the editable flag. Do you know what causes that? If I could make it go into site-packages that would work.

**Comment by adamchainz** [comment]
So I've been thinking about this and looking at importlib a bit, and I am not sure there's a reliable way to detect third party packages. I'm considering instead have the current detection as a first line, and if that doesn't work tell users to define `FIRST_PARTY_APPS` in their settings, e.g.

```python
FIRST_PARTY_APPS ["core", ...]
INSTALLED_APPS = FIRST_PARTY_APPS + ["somepackage", "django.contrib.auth", ...]
```

**Comment by pcraciunoiu** [comment]
That'd be fine, I almost went that route myself. Seems the simplest and most reliable, unfortunately.

I also thought about checking if the app directory is version controlled by git, but that seems like it could cause issues too... (what if people don't use git, what about the server side, etc)

**Comment by adamchainz** [comment]
I've created the `FIRST_PARTY_APPS` setting over in #40, so closing this.

**Comment by pcraciunoiu** [comment]
Thank you @adamchainz . Will try it out soon, should be all good now.

**Pull request closed without merging**
