### PR TITLE
Fix typing

### PR DESCRIPTION
**Pull request by nmzgnv**
https://docs.python.org/3/library/__future__.html
and
https://docs.python.org/3/library/typing.html#typing.Generator

### CODE REVIEW

**Comment by adamchainz** [comment]
Why? I want postponed annotations on in my type hints. They don’t break anything.

**Comment by adamchainz** [comment]
I still don’t understand why you made this PR. If you saw an error with a type checker I’d be interested to know.

**Comment by nmzgnv** [comment]
Yes, there was a type checking error (I don’t remember the text now), but it was solved by updating packages

**Comment by adamchainz** [comment]
Thanks for the info. It may be useful for someone searching the repo in the future for typing issues.

**Pull request closed without merging**
